apiVersion: 1

datasources:
  - name: Infinity-IAM
    type: yesoreyeram-infinity-datasource
    uid: infinity-iam
    access: proxy
    url: http://iam-api:5500
    isDefault: true
    editable: true
    jsonData:
      auth_method: oauth2
      oauthPassThru: false
      oauth2:
        oauth2_type: client_credentials
        client_id: ${GRAFANA_CLIENT_ID}
        token_url: http://iam-api:5500/api/auth/token
      allowedHosts:
        - http://iam-api:5500       
        - http://localhost:5500
    secureJsonData:
      oauth2ClientSecret: ${GRAFANA_CLIENT_SECRET}
