apiVersion: 1

datasources:
  - name: InfluxDB-IAM
    type: influxdb
    uid: influxdb-iam
    access: proxy
    # InfluxDB 2.x uses Flux query language
    url: http://iam-influxdb:8086
    jsonData:
      version: Flux
      organization: iam-org
      defaultBucket: telemetry
      tlsSkipVerify: true
    secureJsonData:
      token: iam-influxdb-admin-token
    isDefault: true
    editable: true
