[server]
http_port = 3000 # Grafana will be accessible on this port
root_url = http://localhost:5500/grafana/ # Root URL for Grafana, adjust if using a different path or domain
serve_from_sub_path = true # Set to true if Grafana is served from a subpath (e.g. /grafana)

[security]
disable_gravatar = true # Disable Gravatar to avoid external calls for user avatars
allow_embedding = true # Allow Grafana to be embedded in iframes (e.g. for embedding dashboards in other apps)
cookie_samesite = lax # Set SameSite attribute for cookies to lax for better security while allowing embedding
cookie_secure = false # Set to true if using HTTPS to ensure cookies are only sent over secure connections
disable_initial_admin_password_change = true # Disable forced password change on first login since we're using JWT auth and not local Grafana users

[auth]
login_maximum_inactive_lifetime_duration = 30d # Users will be logged out after 30 days of inactivity
login_maximum_lifetime_duration = 30d # Maximum lifetime of a login session is 30 days, after which the user must log in again
token_rotation_interval_minutes = 10 # Rotate authentication tokens every 10 minutes for improved security

[auth.anonymous]
enabled = false # Disable anonymous access to Grafana

[auth.jwt]
enabled = true # Enable JWT authentication
header_name = X-JWT-Assertion # The header where Grafana will look for the JWT token
expected_audience = IAM.ReactClient
email_claim = email
username_claim = email
role_attribute_path = contains(roles[*], 'Admin') && 'Admin' || 'Viewer'
jwk_set_file = /etc/grafana/jwks/jwks.json # Path to the JWKS file containing public keys for verifying JWT tokens
cache_ttl = 60m # Cache the JWKS keys for 60 minutes to improve performance       
expected_issuer = IAM.API # Expected issuer in the JWT token, adjust if your tokens have a different issuer
auto_sign_up = true # Automatically create Grafana user accounts for valid JWT tokens that don't have a corresponding Grafana user
;url_login = true 
; enable_login_token = true

[users]
allow_sign_up = false # Disable Grafana's own sign-up page since we're using JWT auth
auto_assign_org = true # Automatically assign new users to the default organization
auto_assign_org_id = 1 # ID of the organization to which new users will be assigned
default_role = Viewer # Default role for new users created via JWT auth
default_theme = dark

[log]
mode = console # Log to console
level = debug # Set log level to debug for detailed logs during development

[database]
type = sqlite3
path = /var/lib/grafana/grafana.db

[alerting]
enabled = true # Enable alerting features in Grafana

[dashboards]
min_refresh_interval = 1s



# we use lax , 
# there is strict also , means cookie only send when request originates from same site.
#if user click from anouther website -> cookie will not be sent,
# for example , if we are on localhost and click click to clocalhost/grafana -> cookie will be sent because it is same site
# but if we are on anotherwebsite.com and click to localhost/grafana -> cookie will not be sent because it is cross site request. This can help prevent CSRF attacks but can also

# now lax means 

