[server]
http_port = 3000
root_url = http://localhost/grafana/
serve_from_sub_path = true

[security]
admin_user = admin
admin_password = admin
secret_key = your-secret-key-change-in-production
disable_gravatar = true
allow_embedding = true
cookie_samesite = lax
cookie_secure = false
disable_initial_admin_password_change = true

[auth]
login_maximum_inactive_lifetime_duration = 30d
login_maximum_lifetime_duration = 30d
token_rotation_interval_minutes = 10

[auth.anonymous]
enabled = false

[auth.jwt]
enabled = true
header_name = X-JWT-Assertion
expected_audience = IAM.ReactClient
email_claim = email
username_claim = sub
roles_claim = roles
jwk_set_file = /etc/grafana/jwks/jwks.json
cache_ttl = 60m             
expected_issuer = IAM.API
auto_sign_up = true
; url_login = true
; enable_login_token = true

[users]
allow_sign_up = false
auto_assign_org = true
auto_assign_org_id = 1
default_role = Viewer
default_theme = dark

[log]
mode = console
level = debug

[database]
type = sqlite3
path = /var/lib/grafana/grafana.db

[alerting]
enabled = true